import React from 'react';
import { Download } from 'lucide-react';
import { useSceneStore } from '../store/sceneStore';
import { usePostProcessingStore } from '../store/postProcessingStore';

export function ExportGameButton() {
  const { objects } = useSceneStore();
  const { exportSettings } = usePostProcessingStore();

  const exportScene = () => {
    const postProcessing = exportSettings();
    
    const sceneData = {
      metadata: {
        version: '1.0.0',
        generator: 'GD3D Editor',
        exportDate: new Date().toISOString().split('T')[0]
      },
      scene: {
        background: '#87ceeb',
        fog: {
          enabled: true,
          color: '#87ceeb',
          near: 50,
          far: 200
        }
      },
      postProcessing: postProcessing,
      objects: objects.filter(obj => !obj.isPlayer).map(obj => {
        const exportObj = {
          id: obj.id,
          name: obj.name,
          type: obj.type,
          position: [obj.position.x, obj.position.y, obj.position.z],
          rotation: [obj.rotation.x, obj.rotation.y, obj.rotation.z],
          scale: [obj.scale.x, obj.scale.y, obj.scale.z]
        };

        // Add GLTF model path
        if (obj.type === 'gltf' && obj.modelPath) {
          exportObj.modelPath = obj.modelPath.replace('../src/assets/', './assets/');
        }

        // Add mesh geometry data
        if ((obj.type === 'mesh' || obj.type === 'primitive') && obj.geometry) {
          exportObj.geometry = obj.geometry.type;
          exportObj.geometryParams = obj.geometry.parameters;
          exportObj.color = obj.material?.color?.getHex() || 0xcccccc;
        }

        // Add physics data
        if (obj.physics && obj.physics.enabled) {
          exportObj.physics = {
            enabled: true,
            mass: obj.physics.mass || 1,
            isStatic: obj.physics.isStatic || false,
            shape: obj.physics.shape || 'auto'
          };
        }

        // Add collision frames data
        if (obj.collisionFrames && obj.collisionFrames.length > 0) {
          exportObj.collisionFrames = obj.collisionFrames.map(frame => ({
            id: frame.id,
            type: frame.type,
            position: frame.position,
            size: frame.size,
            rotation: frame.rotation,
            radius: frame.radius,
            autoGenerated: frame.autoGenerated || false
          }));
        }

        // Mark player character
        if (obj.isPlayer) {
          exportObj.isPlayer = true;
        }

        return exportObj;
      })
    };

    // Create JSON file
    const jsonString = JSON.stringify(sceneData, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    // Download JSON
    const a = document.createElement('a');
    a.href = url;
    a.download = 'scene.json';
    a.click();
    URL.revokeObjectURL(url);

    // Show instructions
    showExportInstructions();
  };

  const showExportInstructions = () => {
    const instructions = `
🎮 Scene Exported Successfully!

Next steps:
1. Save the downloaded scene.json to: gd3d-editor/gameplayer/
2. Copy your 3D models (.glb files) to: gd3d-editor/gameplayer/assets/models/
3. Open gd3d-editor/gameplayer/index.html in your browser
4. Click "Start Game" and play!

📦 To share your game:
- Zip the entire gameplayer folder
- Upload to a web server
- Or share the zip file

✨ Your game includes:
- Early morning skybox with clouds
- Realistic lighting and shadows
- Character controller (WASD + Jump)
- Full physics simulation with collision frames
- Static platforms and dynamic objects
- Custom collision shapes support
- No installation needed!
    `.trim();

    alert(instructions);
  };

  return (
    <button
      onClick={exportScene}
      className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-lg hover:from-purple-600 hover:to-pink-600 transition-all shadow-lg hover:shadow-xl"
      title="Export scene as standalone game"
    >
      <Download size={18} />
      <span className="font-medium">Export Game</span>
    </button>
  );
}
